# local DB
spring:
  datasource:
    url: jdbc:h2:file:./localdb;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:

# # PostgreSQL DB
#   datasource:
#      url: jdbc:postgresql://localhost:5432/postgres
#      username: postgres
#       password: 1234
#       driver-class-name: org.postgresql.Driver

# Redis
       
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JPA
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
     properties:
       hibernate:
         format_sql: true

# CORS
cors.allowed-origins=http://localhost:3000,http://localhost:5173
server.port=8080

# \uC11C\uBC84 \uC751\uB2F5 \uC5D0\uB7EC \uB178\uCD9C\uD558\uC9C0 \uC54A\uC74C
spring.web.error.include-stacktrace=never

# JWT
jwt.secret=sdflkjernklsdfgnruioegnlserjngls
jwt.expiration=3600000