CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS profile (
    user_id BIGINT PRIMARY KEY,
    nickname VARCHAR(50) NOT NULL,
    tag INTEGER NOT NULL,
    bio TEXT NULL,
    affiliation VARCHAR(50) NULL,
    image_url VARCHAR(255) NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES users(id)
);
