-- Reset schema to avoid stale table definitions across test contexts.
DROP TABLE IF EXISTS code_battle_match;

DROP TABLE IF EXISTS code_battle_example_ai;

DROP TABLE IF EXISTS code_battle_participant;

DROP TABLE IF EXISTS code_battle_submission;

DROP TABLE IF EXISTS contest_reviewer;

DROP TABLE IF EXISTS code_battle_contest;

DROP TABLE IF EXISTS profile;

DROP TABLE IF EXISTS users;

-- users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

-- profile
CREATE TABLE IF NOT EXISTS profile (
    user_id BIGINT PRIMARY KEY,
    nickname VARCHAR(50) NOT NULL,
    tag INTEGER NOT NULL,
    affiliation VARCHAR(50) NULL,
    bio TEXT NULL,
    image_url VARCHAR(255) NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- code_battle_contest (status, certification 타입 단순화)
CREATE TABLE IF NOT EXISTS code_battle_contest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    creator_id BIGINT,
    time_limit_sec INTEGER NOT NULL,
    memory_limit_mb INTEGER NOT NULL,
    max_participants INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,
    certification BOOLEAN NOT NULL,
    judge_code TEXT NULL,
    sample_code TEXT NULL,
    start_date TIMESTAMP NULL,
    end_date TIMESTAMP NULL,
    visualization_html_url VARCHAR(255) NULL,
    solo_play_html_url VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT fk_contest_user FOREIGN KEY (creator_id) REFERENCES users (id)
);

-- code_battle_submission
CREATE TABLE IF NOT EXISTS code_battle_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    contest_id BIGINT NULL,
    language VARCHAR(255) NOT NULL,
    code_url TEXT NULL,
    result VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_submission_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_submission_contest FOREIGN KEY (contest_id) REFERENCES code_battle_contest (id)
);

-- code_battle_participant
CREATE TABLE IF NOT EXISTS code_battle_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    contest_id BIGINT NULL,
    score INTEGER NULL,
    submission_id BIGINT NULL,
    is_manual BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_participant_user_contest UNIQUE (user_id, contest_id),
    CONSTRAINT fk_participant_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_participant_contest FOREIGN KEY (contest_id) REFERENCES code_battle_contest (id),
    CONSTRAINT fk_participant_submission FOREIGN KEY (submission_id) REFERENCES code_battle_submission (id)
);

-- code_battle_example_ai
CREATE TABLE IF NOT EXISTS code_battle_example_ai (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id BIGINT NULL,
    example_order INTEGER NULL,
    description TEXT NULL,
    code TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_example_ai_contest FOREIGN KEY (contest_id) REFERENCES code_battle_contest (id)
);

-- code_battle_match
CREATE TABLE IF NOT EXISTS code_battle_match (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id BIGINT NULL,
    user1_id BIGINT NULL,
    user2_id BIGINT NULL,
    winner_id BIGINT NULL,
    log TEXT NULL,
    ai_order BIGINT NULL,
    submission_id BIGINT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_match_contest FOREIGN KEY (contest_id) REFERENCES code_battle_contest (id),
    CONSTRAINT fk_match_user1 FOREIGN KEY (user1_id) REFERENCES users (id),
    CONSTRAINT fk_match_user2 FOREIGN KEY (user2_id) REFERENCES users (id)
);

-- contest_reviewer
CREATE TABLE IF NOT EXISTS contest_reviewer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id BIGINT NOT NULL,
    reviewer_email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contest_reviewer_contest FOREIGN KEY (contest_id) REFERENCES code_battle_contest (id) ON DELETE CASCADE,
    CONSTRAINT uk_contest_reviewer_email UNIQUE (contest_id, reviewer_email)
);