# git action workflow name
name: cd-server
# executing name, can use environment variables
run-name: "CD actor : ${{github.actor}}"
# Controls when the workflow will run
on:
  push:
    branches: ["dev/server"]
    paths:
      - 'server/**'
      - '.github/workflows/*'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs: 
      server_change:  ${{steps.filter_server.outputs.server || 'false'}}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v4
        name: check if server directory exits
        if: hashFiles('server/**') !=  ''
        id: filter_server
        with:
          filters: |
            server:
              - 'server/**'
              - '.github/workflows/*'

  server:
    needs: filter
    if: needs.filter.outputs.server_change == 'true'
    permissions: 
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    env: 
      DB_USER: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_NAME_STAGING }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL_STAGING }}
      JWT_TOKEN: ${{secrets.JWT_TOKEN}}
      GMAIL_PASSWORD: ${{secrets.GMAIL_PASSWORD}}
      SOL_API_KEY: ${{secrets.SOL_API_KEY}}
      SOL_API_SECRET: ${{secrets.SOL_API_SECRET}}
      SOL_SENDER_NUMBER: ${{secrets.SOL_SENDER_NUMBER}}
      TOSS_CLIENT_KEY: ${{secrets.TOSS_CLIENT_KEY}}
      TOSS_SECRET_KEY: ${{secrets.TOSS_SECRET_KEY}}
      
    steps:
      - uses: actions/checkout@v4
      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
     
      - name: add permission to execute
        run: chmod +x gradlew 

      - name: server test
        run: ./gradlew test jacocoTestReport
      - name: server build
        run: ./gradlew build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ARN_ROLE}}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2 

      - name: Build and push Docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: caps-asap-server
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Upload deploy.sh to S3
        run: |
          aws s3 cp deploy.sh s3://caps-asap-bucket-test/backend-deploy/deploy/deploy.sh

      - name: Upload JaCoCo report to S3
        run: |
          aws s3 sync build/reports/jacoco/test/html/ \
          s3://caps-asap-bucket-test/backend-deploy/jacoco/${{ github.sha }}/

      - name: Start EC2 and Wait
        run: |
          aws ec2 start-instances --instance-ids ${{ vars.EC2_ID_INSTANCE }}
          aws ec2 wait instance-running --instance-ids ${{ vars.EC2_ID_INSTANCE }}
          
      - name: Wait for SSM ready
        run: |
          echo "Waiting for SSM Agent to be online..."
          i=0
          while true; do
            STATUS=$(aws ssm describe-instance-information \
              --filters "Key=InstanceIds,Values=${{ vars.EC2_ID_INSTANCE }}" \
              --query "InstanceInformationList[0].PingStatus" \
              --output text)
            
            if [ "$STATUS" = "Online" ]; then
              echo "SSM Agent is Online!"
              break
            fi

            if [ "$i" -ge 24 ]; then # 5초 * 36 = 120초
              echo "SSM Agent did not become online in time."
              exit 1
            fi
            
            echo "Current status: $STATUS. Waiting 5s... ($i)"
            i=$((i+1))
            sleep 5
          done

      - name: Run deploy on EC2
        env:
          ECR_IMAGE: ${{ steps.build-image.outputs.image }}
        run: |
          COMMAND_ID=$(aws ssm send-command \
          --instance-ids ${{vars.EC2_ID_INSTANCE}} \
          --document-name "AWS-RunShellScript" \
          --parameters '{
            "commands": [
              "export HOME=/home/ubuntu",
              "mkdir -p /home/ubuntu/app",
              "cd /home/ubuntu/app",
              
              "aws s3 cp s3://caps-asap-bucket-test/backend-deploy/deploy/deploy.sh .",

              "cat > /home/ubuntu/app/.env << 'EOF'",
              "DB_URL=${{secrets.DB_URL_STAGING}}",
              "DB_NAME=${{secrets.DB_NAME_STAGING}}",
              "DB_USER=${{secrets.DB_USER}}",
              "DB_PASSWORD=${{secrets.DB_PASSWORD}}",
              "JWT_TOKEN=${{secrets.JWT_TOKEN}}",
              "GMAIL_PASSWORD=${{secrets.GMAIL_PASSWORD}}",
              "SOL_API_KEY=${{secrets.SOL_API_KEY}}",
              "SOL_API_SECRET=${{secrets.SOL_API_SECRET}}",
              "SOL_SENDER_NUMBER=${{secrets.SOL_SENDER_NUMBER}}",
              "AWS_REGION=${{ vars.AWS_REGION }}",
              "AWS_BUCKET_TEST=${{secrets.AWS_BUCKET_TEST}}",
              "AWS_CLOUD_FRONT=${{vars.AWS_CLOUD_FRONT}}",
              "AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}",
              "AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}",
              "TOSS_CLIENT_KEY=${{secrets.TOSS_CLIENT_KEY}}",
              "TOSS_SECRET_KEY=${{secrets.TOSS_SECRET_KEY}}",
              "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}",
              "EOF",

              "chmod 600 .env",
              "chmod +x deploy.sh",
              "bash deploy.sh ${{steps.build-image.outputs.image}}"
            ]
          }' \
          --query "Command.CommandId" \
          --output text)

          aws ssm wait command-executed \
          --command-id $COMMAND_ID \
          --instance-id ${{vars.EC2_ID_INSTANCE}} \
          --cli-read-timeout 600 \
          --cli-connect-timeout 60 \
          --waiter-config '{"Delay": 15, "MaxAttempts": 60}'
