# git action workflow name
name: ci-server
# executing name: actor name
run-name: "CI actor : ${{github.actor}}"
# Controls when the workflow will run
on:
  push: 
    branches: ["main"]
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/*'

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: add permission to execute
        run: chmod +x gradlew 

      - name: server Test
        run: ./gradlew test
      
      - name: server Build
        run: ./gradlew build
