# git action workflow name
name: ci
# executing name, can use environment variables
run-name: "actor : ${{github.actor}}"
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main, "test_br", "dev/server", "dev/front" ]
      # 실행할 경로를 아래 경로 파일들의 변동으로 제한
    paths:
      - 'front/**'
      - 'server/**'
      - '.github/workflows/*'
  pull_request:
    branches: [ "main", test_br ]
    paths:
      - 'front/**'
      - 'server/**'
      - '.github/workflows/*'

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  filter:
    runs-on: ubuntu-latest
    outputs: 
      server_change:  ${{steps.filter.outputs.server}}
      front_change: ${{steps.filter.outputs.front}}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            front:
              -  'front/**'
              -  '.github/workflows/*'
            server:
              - 'server/**'
              - '.github/workflows/*'

  # This workflow contains a single job called "build"
  front:
    needs: filter
    if: needs.filter.outputs.front_change == 'true'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # default setting
    defaults:
      run:
        working-directory: front
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: node install
        with:
          node-version: 18
      - name: install npm
        run: npm ci

      - name: npm test
        run: |
          npm test -- --watchAll=false --passWithNoTests

      - name: npm build
        run: npm run build

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ARN_ROLE}}
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload to S3BUCKET
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync build/ s3://caps-asap-bucket --delete
      - name: Upload to S3BUCKET for Test
        if: github.ref != 'refs/heads/main'
        run: aws s3 sync build/ s3://caps-asap-bucket-test --delete
        


  server:
    needs: filter
    if: needs.filter.outputs.server_change == 'true'

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: add permission to execute
        run: chmod +x gradlew 
      - name: server build
        run: ./gradlew build
      - name: server test
        run: ./gradlew test
      - name: aws-ec2 test
        run: echo "not implemented"

  aws-front-server-test:
    if: false
    needs: [server, front]
    runs-on: ubuntu-latest
    defaults: 
      run:
        working_directory: server 
    steps:
      - uses: actions/checkout@v4

  aws-build:
    if: false
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ARN_ROLE}}
          #role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}
      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: chmod
        run: chmod -R +x ./.github

      - name: Build and Package Maven
        id: package
        working-directory: ${{ env.applicationfolder }}
        run: $GITHUB_WORKSPACE/.github/scripts/build.sh

      - name: Upload Artifact to s3
        working-directory: ${{ env.applicationfolder }}/target
        run: aws s3 cp *.war s3://${{ env.S3BUCKET }}
        
  aws-deploy:
  if: false
    needs: aws-build
    runs-on: ubuntu-latest
    environment: Dev

    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}
    - run: |
        echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
        commit_hash=`git rev-parse HEAD`
        aws deploy create-deployment --application-name CodeDeployAppNameWithASG --deployment-group-name CodeDeployGroupName --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures

    
